# Generated by Django 5.2.8 on 2026-01-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('assistant_type', models.CharField(choices=[('neuro_tutor', 'Нейро-репетитор'), ('tech_expert', 'Технический эксперт'), ('career_coach', 'Карьерный коуч'), ('conversation_partner', 'Партнер для разговорной практики')], max_length=50, verbose_name='Тип ассистента')),
                ('system_prompt', models.TextField(verbose_name='Системный промпт')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Температура')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='Макс. токены')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Специализация')),
                ('target_audience', models.CharField(blank=True, max_length=100, verbose_name='Целевая аудитория')),
                ('learning_goals', models.JSONField(blank=True, default=list, null=True, verbose_name='Цели обучения')),
                ('teaching_methods', models.JSONField(blank=True, default=list, null=True, verbose_name='Методы обучения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI-ассистент',
                'verbose_name_plural': 'AI-ассистенты',
                'indexes': [models.Index(fields=['slug'], name='ai_assistan_slug_66cf69_idx'), models.Index(fields=['assistant_type'], name='ai_assistan_assista_1495da_idx')],
            },
        ),
    ]
