# Generated by Django 5.2.8 on 2025-12-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistant',
            name='learning_goals',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Цели обучения'),
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='teaching_methods',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Методы обучения'),
        ),
    ]
