# Generated by Django 5.2.8 on 2025-11-16 07:47

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2)),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('open', 'Open Answer'), ('reading', 'Понимание текст')], db_index=True, max_length=10)),
                ('question_text', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, help_text='Варианты для MCQ (список строк). Для open = null', null=True, size=None)),
                ('correct_answer', models.JSONField(blank=True, help_text='{"index": 0} для MCQ или {"text":"..."} для точной проверки', null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level'],
                'indexes': [models.Index(fields=['level', 'type'], name='assessment__level_35db11_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMGeneratedQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_id', models.CharField(blank=True, help_text='Опциональный ID промпта/шаблона', max_length=128, null=True)),
                ('user_id', models.UUIDField(db_index=True, help_text='UUID пользователя, для которого сгенерирован вопрос')),
                ('test_session_id', models.UUIDField(db_index=True, help_text='ID TestSession при генерации')),
                ('question_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='assessment__user_id_3ede3c_idx'), models.Index(fields=['test_session_id'], name='assessment__test_se_d80758_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(default=60, help_text='Время жизни сессии в минутах')),
                ('locked_by', models.CharField(blank=True, help_text="Кто в настоящий момент 'держит' сессию (web/telegram/worker)", max_length=32, null=True)),
                ('estimated_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2, null=True)),
                ('protocol_json', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('cefr', 'Статический CEFR из банка'), ('llm', 'Сгенерирован LLM')], db_index=True, max_length=10)),
                ('source_question_id', models.UUIDField(help_text='ID в CEFRQuestion или LLMGeneratedQuestion')),
                ('question_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.testsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_audio_url', models.URLField(blank=True, null=True)),
                ('recognized_text', models.TextField(blank=True, help_text='STT result если был voice', null=True)),
                ('score', models.FloatField(blank=True, help_text='Оценка 0.0–1.0', null=True)),
                ('ai_feedback', models.JSONField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.questioninstance')),
            ],
            options={
                'indexes': [models.Index(fields=['question', 'answered_at'], name='assessment__questio_445365_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['user_id', 'started_at'], name='assessment__user_id_e98f75_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['estimated_level'], name='assessment__estimat_ebcf72_idx'),
        ),
        migrations.AddIndex(
            model_name='questioninstance',
            index=models.Index(fields=['session', 'created_at'], name='assessment__session_2b5987_idx'),
        ),
        migrations.AddIndex(
            model_name='questioninstance',
            index=models.Index(fields=['source_type'], name='assessment__source__9b7fc5_idx'),
        ),
    ]
