# Generated by Django 5.2.8 on 2025-11-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cefrquestion',
            name='type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('open', 'Open Answer'), ('reading', 'Understanding Text')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='locked_by',
            field=models.CharField(choices=[('web', 'Сессия начата на сайте'), ('tg', 'Сессия начата в боте')], default='web', help_text="Кто в настоящий момент 'держит' сессию (web/telegram)", max_length=32),
        ),
    ]
