# Generated by Django 5.2.8 on 2026-02-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('curriculum', '0010_task_learning_objectives_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CEFRQuestion',
        ),
        migrations.DeleteModel(
            name='LLMGeneratedQuestion',
        ),
        migrations.RemoveIndex(
            model_name='questioninstance',
            name='assessment__source__9b7fc5_idx',
        ),
        migrations.RemoveField(
            model_name='questioninstance',
            name='question_json',
        ),
        migrations.RemoveField(
            model_name='questioninstance',
            name='source_question_id',
        ),
        migrations.RemoveField(
            model_name='questioninstance',
            name='source_type',
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_instances', to='curriculum.task'),
        ),
    ]
