# Generated by Django 5.2.8 on 2026-02-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_delete_cefrquestion_delete_llmgeneratedquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='test_answer_media/', verbose_name='File')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='assessment.testanswer', verbose_name='Task')),
            ],
        ),
    ]
