# Generated by Django 5.2.8 on 2025-11-24 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_cefrquestion_type_alter_testsession_locked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.questioninstance'),
        ),
    ]
