# Generated by Django 5.2.8 on 2025-11-25 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_testanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cefrquestion',
            name='level',
            field=models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='assessment.questioninstance'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='estimated_level',
            field=models.CharField(blank=True, choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], db_index=True, max_length=2, null=True),
        ),
    ]
