# Generated by Django 5.2.8 on 2026-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_testanswermedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testanswer',
            name='answer_audio_url',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='recognized_text',
        ),
        migrations.AddField(
            model_name='testanswer',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='test_answer_media/', verbose_name='Audio Response'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='response_text',
            field=models.TextField(blank=True, verbose_name='Text Response'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Audio Transcript'),
        ),
    ]
