# Generated by Django 5.2.8 on 2026-01-26 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_coursebalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogLLMRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
                ('model_name', models.CharField(help_text="e.g., 'gpt-4o-mini'", max_length=50, verbose_name='Имя модели')),
                ('prompt', models.TextField(help_text='Полный текст запроса к LLM', verbose_name='Промпт запроса')),
                ('response', models.TextField(blank=True, help_text='Полный ответ, включая JSON', verbose_name='Ответ LLM')),
                ('tokens_in', models.PositiveIntegerField(default=0, verbose_name='Токены на вход')),
                ('tokens_out', models.PositiveIntegerField(default=0, verbose_name='Токены на выход')),
                ('cost_in', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Стоимость входа')),
                ('cost_out', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Стоимость выхода')),
                ('cost_total', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительный контекст запроса', verbose_name='Метаданные')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успех'), ('ERROR', 'Ошибка'), ('TIMEOUT', 'Таймаут')], default='SUCCESS', max_length=20, verbose_name='Статус')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to='curriculum.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to='curriculum.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'LLM Log',
                'verbose_name_plural': 'LLM Logs',
                'ordering': ['-request_time'],
                'indexes': [models.Index(fields=['request_time'], name='llm_logger__request_d75486_idx'), models.Index(fields=['model_name'], name='llm_logger__model_n_17862c_idx'), models.Index(fields=['status'], name='llm_logger__status_d1eac1_idx'), models.Index(fields=['user', 'course', 'lesson'], name='llm_logger__user_id_0155cc_idx')],
            },
        ),
    ]
