# Generated by Django 5.2.8 on 2026-01-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logllmrequest',
            name='duration_sec',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность генерации, сек'),
        ),
        migrations.AddField(
            model_name='logllmrequest',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Сообщение об ошибке'),
        ),
    ]
