# Generated by Django 5.2.8 on 2026-01-28 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_lesson_content_ru_alter_lesson_content'),
        ('llm_logger', '0002_logllmrequest_duration_sec_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logllmrequest',
            name='llm_logger__user_id_0155cc_idx',
        ),
        migrations.RenameIndex(
            model_name='logllmrequest',
            new_name='llm_request_time_idx',
            old_name='llm_logger__request_d75486_idx',
        ),
        migrations.RenameIndex(
            model_name='logllmrequest',
            new_name='llm_model_name_idx',
            old_name='llm_logger__model_n_17862c_idx',
        ),
        migrations.RenameIndex(
            model_name='logllmrequest',
            new_name='llm_status_idx',
            old_name='llm_logger__status_d1eac1_idx',
        ),
        migrations.AddField(
            model_name='logllmrequest',
            name='request_type',
            field=models.CharField(choices=[('COURSE_GEN', 'Генерация курса'), ('LESSON_GEN', 'Генерация урока'), ('LESSON_REVIEW', 'Оценка урока'), ('TASK_GEN', 'Генерация задания'), ('TASK_REVIEW', 'Оценка задания'), ('CHAT', 'Чат с AI'), ('DIAGNOSTIC', 'Диагностика'), ('FEEDBACK', 'Фидбэк студенту'), ('OTHER', 'Другое')], default='OTHER', help_text='Классификация запроса для аналитики', max_length=50, verbose_name='Тип запроса'),
        ),
        migrations.AddField(
            model_name='logllmrequest',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to='curriculum.task', verbose_name='Задание'),
        ),
        migrations.AddIndex(
            model_name='logllmrequest',
            index=models.Index(fields=['request_type'], name='llm_request_type_idx'),
        ),
        migrations.AddIndex(
            model_name='logllmrequest',
            index=models.Index(fields=['request_type', '-request_time'], name='llm_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logllmrequest',
            index=models.Index(fields=['model_name', '-request_time'], name='llm_model_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logllmrequest',
            index=models.Index(fields=['status', '-request_time'], name='llm_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logllmrequest',
            index=models.Index(fields=['user', '-request_time'], name='llm_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logllmrequest',
            index=models.Index(fields=['course', '-request_time'], name='llm_course_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logllmrequest',
            index=models.Index(fields=['lesson', '-request_time'], name='llm_lesson_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logllmrequest',
            index=models.Index(fields=['task', '-request_time'], name='llm_task_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logllmrequest',
            index=models.Index(fields=['cost_total'], name='llm_cost_total_idx'),
        ),
        migrations.AddIndex(
            model_name='logllmrequest',
            index=models.Index(fields=['metadata'], name='llm_metadata_idx'),
        ),
    ]
