# Generated by Django 5.2.8 on 2026-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_logger', '0003_remove_logllmrequest_llm_logger__user_id_0155cc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logllmrequest',
            name='response_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Ответ LLM (структура)'),
        ),
        migrations.AlterField(
            model_name='logllmrequest',
            name='response',
            field=models.TextField(blank=True, help_text='Полный ответ, включая JSON', verbose_name='Ответ LLM (текстовый)'),
        ),
    ]
