# Generated by Django 5.2.8 on 2026-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_logger', '0004_logllmrequest_response_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logllmrequest',
            name='response',
            field=models.TextField(blank=True, help_text='Текстовый ответ от LLM', null=True, verbose_name='Ответ LLM (текстовый)'),
        ),
        migrations.AlterField(
            model_name='logllmrequest',
            name='response_json',
            field=models.JSONField(blank=True, help_text='Структурированный JSON ответ от LLM', null=True, verbose_name='Ответ LLM (структура)'),
        ),
    ]
