# Generated by Django 5.2.8 on 2026-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_logger', '0005_alter_logllmrequest_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logllmrequest',
            name='prompt',
            field=models.JSONField(help_text='Полный текст запроса к LLM', verbose_name='Промпт запроса'),
        ),
    ]
