# Generated by Django 5.2.8 on 2026-02-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_testanswer_evaluation_status'),
        ('llm_logger', '0006_alter_logllmrequest_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='logllmrequest',
            name='test_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to='assessment.testsession', verbose_name='Тестовая сессия'),
        ),
        migrations.AlterField(
            model_name='logllmrequest',
            name='request_type',
            field=models.CharField(choices=[('COURSE_GEN', 'Генерация курса'), ('LESSON_GEN', 'Генерация урока'), ('TEST TASK REVIEW', 'Оценка тестового задания'), ('TEST SESSION REVIEW', 'Оценка тестовой сессии'), ('LESSON_REVIEW', 'Оценка урока'), ('TASK_GEN', 'Генерация задания'), ('TASK_REVIEW', 'Оценка задания'), ('CHAT', 'Чат с AI'), ('DIAGNOSTIC', 'Диагностика'), ('FEEDBACK', 'Фидбэк студенту'), ('OTHER', 'Другое')], default='OTHER', help_text='Классификация запроса для аналитики', max_length=50, verbose_name='Тип запроса'),
        ),
    ]
