# Generated by Django 5.2.8 on 2026-01-19 17:20

import curriculum.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_student_teacher_delete_studyprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('estimated_duration', models.PositiveIntegerField(help_text='Total estimated time to complete the course', verbose_name='Estimated Duration (minutes)')),
                ('required_skills', models.JSONField(default=list, help_text="e.g., ['grammar:B1', 'listening:A2']", verbose_name='Required Skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptive_path_enabled', models.BooleanField(default=False, verbose_name='Адаптивный путь активен')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('lesson_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED_TASKS', 'All tasks completed'), ('PENDING_ASSESSMENT', 'Pending assessment'), ('ASSESSMENT_ERROR', 'Assessment error'), ('COMPLETED', 'Lesson completed')], default='ACTIVE', max_length=20, verbose_name='Lesson Status')),
                ('assessment_job_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assessment Job ID')),
                ('assessment_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Assessment Started At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_level', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], help_text='Уровень CEFR, на котором эта цель актуальна', max_length=2, verbose_name='CEFR Level')),
                ('skill_domain', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], help_text='Область языкового навыка', max_length=20, verbose_name='Skill Domain')),
                ('order_in_level', models.PositiveSmallIntegerField(default=1, help_text='Порядковый номер цели в рамках уровня и области (для сортировки)', verbose_name='Order within level and domain')),
                ('name', models.CharField(help_text="Clear, actionable objective — e.g., 'Use Past Simple correctly in work emails'", max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional detailed explanation for methodologists', verbose_name='Description')),
                ('identifier', models.SlugField(editable=False, help_text="Auto-generated unique ID like 'grammar-B1-01'", unique=True, verbose_name='Machine Identifier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Learning Objective',
                'verbose_name_plural': 'Learning Objectives',
                'ordering': ['cefr_level', 'skill_domain', 'order_in_level'],
                'indexes': [models.Index(fields=['cefr_level', 'skill_domain'], name='curriculum__cefr_le_a4e68a_idx'), models.Index(fields=['identifier'], name='curriculum__identif_0ab93b_idx')],
                'unique_together': {('cefr_level', 'skill_domain', 'order_in_level')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.ManyToManyField(to='curriculum.learningobjective', verbose_name='Learning Objectives'),
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_type', models.CharField(choices=[('LINEAR', 'Линейный (по порядку уроков курса)'), ('ADAPTIVE', 'Адаптивный (с ветвлениями по SkillDelta)'), ('PERSONALIZED', 'Персонализированный (AI-генерированный под цели/профессию)')], default='LINEAR', max_length=20, verbose_name='Тип пути')),
                ('nodes', models.JSONField(default=list, help_text='\n        Пример структуры:\n        [\n            {\n                "node_id": 1,\n                "lesson_id": 5,\n                "title": "Grammar: Present Simple",\n                "prerequisites": [], \n                "triggers": [\n                    {"condition": "skill_delta.speaking < 0", "action": "add_remedial", "remedial_lesson_id": 12}\n                ],\n                "status": "completed",  // in_progress, locked, recommended\n                "completed_at": "2025-12-28T15:30:00Z"\n            },\n            ...\n        ]\n        ', verbose_name='Узлы пути')),
                ('current_node_index', models.PositiveIntegerField(default=0, help_text='Позиция в массиве nodes', verbose_name='Индекс текущего узла')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время генерации пути')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="e.g., {'generated_by': 'gpt-4o-mini', 'based_on_profile': {'level': 'B1', 'goal': 'IT_interview'}}", verbose_name='Метаданные')),
                ('enrollment', models.OneToOneField(help_text='Один путь на одно зачисление', on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to='curriculum.enrollment', verbose_name='Зачисление')),
            ],
            options={
                'verbose_name': 'Учебный путь',
                'verbose_name_plural': 'Учебные пути',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('content', models.JSONField(help_text='Optional structured lesson instructions or narrative for AI', verbose_name='Content')),
                ('theory_content', models.TextField(blank=True, help_text='HTML content with theory and explanations', verbose_name='Theory Content')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Duration (minutes)')),
                ('required_cefr', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], max_length=2, verbose_name='Required CEFR')),
                ('skill_focus', models.JSONField(default=list, help_text="e.g., ['listening', 'vocabulary']", validators=[curriculum.validators.validate_skill_focus], verbose_name='Skill Focus')),
                ('adaptive_parameters', models.JSONField(default=dict, help_text="e.g., {'min_correct_ratio': 0.7, 'max_items': 10}", verbose_name='Adaptive Parameters')),
                ('is_remedial', models.BooleanField(default=False, verbose_name='дополнительные, корректирующие уроки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.course', verbose_name='Course')),
                ('learning_objectives', models.ManyToManyField(to='curriculum.learningobjective', verbose_name='Learning Objectives')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_enrollments', to='curriculum.lesson', verbose_name='Current Lesson'),
        ),
        migrations.CreateModel(
            name='LessonEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('START', 'Начало урока'), ('COMPLETE', 'Завершение урока'), ('PAUSE', 'Пауза в уроке'), ('RESUME', 'Возобновление урока'), ('ABANDON', 'Покинул урок без завершения'), ('ASSESSMENT_START', 'Начало оценки урока'), ('ASSESSMENT_COMPLETE', 'Завершение оценки урока')], max_length=32, verbose_name='Тип события')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время события')),
                ('channel', models.CharField(choices=[('WEB', 'Веб-приложение'), ('BOT', 'Telegram-бот'), ('API', 'Внешний API')], default='WEB', help_text='Откуда пришло событие — для кросс-канальной аналитики', max_length=20, verbose_name='Канал')),
                ('duration_minutes', models.DecimalField(blank=True, decimal_places=2, help_text='Автоматически рассчитывается для COMPLETE по разнице с START', max_digits=6, null=True, verbose_name='Длительность (мин)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Дополнительные данные: e.g., {'completed_tasks': 8, 'total_tasks': 10, 'score': 0.92}", verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(help_text='Контекст курса и текущего прогресса', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_events', to='curriculum.enrollment', verbose_name='Зачисление')),
                ('lesson', models.ForeignKey(blank=True, help_text='Конкретный урок, к которому относится событие', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='curriculum.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(help_text='Ссылка на профиль студента с уровнем, целями и профессией', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_events', to='users.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Событие урока',
                'verbose_name_plural': 'События уроков',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short, machine-readable name (e.g., 'backend', 'standup-meetings')", max_length=50, unique=True, verbose_name='Tag Name')),
                ('description', models.CharField(blank=True, help_text='Human-readable explanation for admins', max_length=200, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Professional Tag',
                'verbose_name_plural': 'Professional Tags',
                'indexes': [models.Index(fields=['name'], name='curriculum__name_f1db3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_context', models.CharField(choices=[('POST_LESSON', 'После завершения урока'), ('PLACEMENT', 'Результат placement test'), ('WEEKLY_SUMMARY', 'Еженедельный'), ('MANUAL', 'Ручной')], default='POST_LESSON', max_length=20, verbose_name='Контекст снимка')),
                ('grammar', models.FloatField(default=0.0)),
                ('vocabulary', models.FloatField(default=0.0)),
                ('listening', models.FloatField(default=0.0)),
                ('reading', models.FloatField(default=0.0)),
                ('writing', models.FloatField(default=0.0)),
                ('speaking', models.FloatField(default=0.0)),
                ('skills', models.JSONField(default=dict, help_text="{'grammar': 0.85, 'vocabulary': 0.78, 'speaking': 0.65, 'listening': 0.82, ...} — 0.0–1.0", verbose_name='Навыки')),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="e.g., {'source': 'assessment', 'lesson_score': 0.92, 'tasks_completed': 10}", verbose_name='Метаданные')),
                ('associated_lesson', models.ForeignKey(blank=True, help_text='Урок, после завершения которого сделан снимок (POST). Для PRE используем урок, который студент собирается начать.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_snapshots', to='curriculum.lesson', verbose_name='Связанный урок')),
                ('enrollment', models.ForeignKey(help_text='Контекст курса для адаптивных маршрутов', on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='curriculum.enrollment', verbose_name='Зачисление')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='users.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Снимок навыков',
                'verbose_name_plural': 'Снимки навыков',
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deltas', models.JSONField(help_text="{'grammar': +0.10, 'speaking': -0.03, 'overall': +0.08}")),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_deltas', to='curriculum.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_deltas', to='curriculum.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_deltas', to='users.student')),
                ('post_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deltas_as_post', to='curriculum.skillsnapshot')),
                ('pre_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deltas_as_pre', to='curriculum.skillsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20, verbose_name='Task Type')),
                ('response_format', models.CharField(choices=[('multiple_choice', 'Multiple Choice – выбор одного или нескольких вариантов'), ('single_choice', 'Single Choice – выбор одного варианта'), ('short_text', 'Short Text – краткий текстовый ответ, 1–3 слова'), ('free_text', 'Free Text – развёрнутый ответ, абзац или текст'), ('audio', 'Audio – голосовое сообщение')], max_length=20, verbose_name='Response Format')),
                ('content', models.JSONField(verbose_name='Content')),
                ('content_schema_version', models.CharField(default='v1', verbose_name='Content Schema')),
                ('difficulty_cefr', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], max_length=2, verbose_name='Difficulty CEFR')),
                ('is_diagnostic', models.BooleanField(default=False, verbose_name='Used in Diagnostic')),
                ('is_active', models.BooleanField(default=True, verbose_name='Задание актуально')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок задания в уроке (чем меньше число, тем раньше задание)', verbose_name='Порядок задачи в уроке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='curriculum.lesson', verbose_name='Lesson')),
                ('professional_tags', models.ManyToManyField(blank=True, to='curriculum.professionaltag', verbose_name='Professional Tags')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentTaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, verbose_name='Text Response')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='responses/', verbose_name='Audio Response')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Audio Transcript')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_response', to='curriculum.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Student Task Response',
                'verbose_name_plural': 'Student Task Responses',
            },
        ),
        migrations.CreateModel(
            name='TaskMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_media/', verbose_name='File')),
                ('media_type', models.CharField(choices=[('text', 'Raw text snippet or prompt'), ('audio', 'Audio file (e.g., MP3, WAV)'), ('video', 'Video file (e.g AVI, MP4)'), ('image', 'Image (e.g., diagram, screenshot)'), ('document', 'PDF, DOC, or other document')], max_length=20, verbose_name='Media Type')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='curriculum.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task Media',
                'verbose_name_plural': 'Task Media',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='curriculum__course__d8682d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course'], name='curriculum__student_e62215_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active'], name='curriculum__is_acti_e42fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['last_activity'], name='curriculum__last_ac_7ab071_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['lesson_status'], name='curriculum__lesson__c99c06_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['assessment_job_id'], name='curriculum__assessm_d05d5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'course', 'is_active'), name='unique_active_enrollment'),
        ),
        migrations.AddIndex(
            model_name='lessoneventlog',
            index=models.Index(fields=['student', '-timestamp'], name='curriculum__student_6843f8_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoneventlog',
            index=models.Index(fields=['enrollment', 'lesson'], name='curriculum__enrollm_b0f3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoneventlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='curriculum__event_t_fc4121_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoneventlog',
            index=models.Index(fields=['channel'], name='curriculum__channel_b28441_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsnapshot',
            index=models.Index(fields=['student', '-snapshot_at'], name='curriculum__student_78df35_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsnapshot',
            index=models.Index(fields=['enrollment', 'associated_lesson'], name='curriculum__enrollm_a42891_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsnapshot',
            index=models.Index(fields=['snapshot_context'], name='curriculum__snapsho_0dbd5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillsnapshot',
            unique_together={('enrollment', 'associated_lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='skilldelta',
            unique_together={('student', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['lesson', 'order'], name='curriculum__lesson__3a6e05_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='curriculum__task_ty_abb4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['response_format'], name='curriculum__respons_b586c8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['lesson', 'is_active', 'order'], name='task_lesson_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttaskresponse',
            index=models.Index(fields=['student', 'task'], name='response_student_task_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttaskresponse',
            index=models.Index(fields=['task'], name='curriculum__task_id_7a3265_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttaskresponse',
            index=models.Index(fields=['submitted_at'], name='curriculum__submitt_2b5462_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmedia',
            index=models.Index(fields=['task'], name='curriculum__task_id_36bd62_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmedia',
            index=models.Index(fields=['media_type'], name='curriculum__media_t_ff8980_idx'),
        ),
    ]
