# Generated by Django 5.2.8 on 2026-01-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttaskresponse',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttaskresponse',
            unique_together={('enrollment', 'task')},
        ),
        migrations.CreateModel(
            name='LessonAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('structured_feedback', models.JSONField(default=dict)),
                ('llm_summary', models.TextField(blank=True)),
                ('llm_recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидание оценки'), ('PROCESSING', 'Оценка в процессе'), ('COMPLETED', 'Оценка завершена'), ('ERROR', 'Ошибка оценки')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='curriculum.enrollment')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson')),
            ],
            options={
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, help_text='0.0–1.0', null=True)),
                ('is_correct', models.BooleanField(blank=True, help_text='Для closed-заданий', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Краткий комментарий LLM или правила')),
                ('structured_feedback', models.JSONField(blank=True, default=dict, help_text="{'grammar_error': 'Past Simple', 'confidence': 0.92}")),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assessments', to='curriculum.enrollment')),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment', to='curriculum.studenttaskresponse')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.task')),
            ],
            options={
                'indexes': [models.Index(fields=['enrollment', 'task'], name='curriculum__enrollm_e81512_idx'), models.Index(fields=['score'], name='curriculum__score_4b49a2_idx')],
                'unique_together': {('enrollment', 'task')},
            },
        ),
    ]
