# Generated by Django 5.2.8 on 2025-12-23 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('users', '0009_student_teacher_delete_studyprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='skilltrajectory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_trajectories', to='users.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='currentskill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_skills', to='users.student'),
        ),
        migrations.AlterField(
            model_name='teacheroverride',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_overrides', to='users.student'),
        ),
        migrations.AlterField(
            model_name='currentskillprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to='users.student'),
        ),
        migrations.AlterField(
            model_name='skillsnapshot',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='users.student'),
        ),
        migrations.AlterField(
            model_name='studenttaskresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='diagnosticsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Student'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AlterField(
            model_name='teacheroverride',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='users.teacher'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
