# Generated by Django 5.2.8 on 2026-01-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_studenttaskresponse_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learning_objectives',
        ),
        migrations.RemoveField(
            model_name='course',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='course',
            name='professional_tags',
            field=models.ManyToManyField(blank=True, help_text="Теги профессий, для которых курс релевантен (e.g., 'backend', 'qa')", to='curriculum.professionaltag', verbose_name='Professional Tags'),
        ),
        migrations.AlterField(
            model_name='lessoneventlog',
            name='event_type',
            field=models.CharField(choices=[('START', 'Начало урока'), ('COMPLETE', 'Завершение урока'), ('PAUSE', 'Пауза в уроке'), ('RESUME', 'Возобновление урока'), ('ABANDON', 'Покинул урок без завершения'), ('ASSESSMENT_START', 'Начало оценки урока'), ('ASSESSMENT_COMPLETE', 'Завершение оценки урока'), ('ASSESSMENT_ERROR', 'Ошибка оценки урока')], max_length=32, verbose_name='Тип события'),
        ),
    ]
