# Generated by Django 5.2.8 on 2026-01-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_remove_course_estimated_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons', models.PositiveIntegerField(default=120)),
                ('level_distribution', models.JSONField(default=dict, help_text='Процентное распределение уровней')),
                ('skill_distribution', models.JSONField(default=dict, help_text='Баланс навыков')),
                ('frozen', models.BooleanField(default=True, help_text='Запрещает изменение после инициализации')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curriculum.course')),
            ],
            options={
                'verbose_name': 'Course balance',
                'verbose_name_plural': 'Course balances',
            },
        ),
    ]
