# Generated by Django 5.2.8 on 2025-12-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_task_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['lesson', 'order'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='curriculum__difficu_21adcf_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='curriculum__is_diag_82f412_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок задания в уроке (чем меньше число, тем раньше задание)', verbose_name='Порядок задачи в уроке'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['lesson', 'order'], name='curriculum__lesson__3a6e05_idx'),
        ),
    ]
