# Generated by Django 5.2.8 on 2026-01-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_coursebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(blank=True, help_text="Field 'content' in Russian lang", verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Optional structured lesson instructions or narrative for AI', verbose_name='Content'),
        ),
    ]
