# Generated by Django 5.2.8 on 2026-02-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_lesson_content_ru_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='Metadata'),
        ),
    ]
