# Generated by Django 5.2.8 on 2026-02-03 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_lesson_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassessmentresult',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='curriculum.task'),
        ),
    ]
