# Generated by Django 5.2.8 on 2026-02-03 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_taskassessmentresult_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassessmentresult',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment', to='curriculum.studenttaskresponse'),
        ),
        migrations.AlterField(
            model_name='taskassessmentresult',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.task'),
        ),
    ]
