# Generated by Django 5.2.8 on 2026-02-04 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_alter_taskassessmentresult_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='nodes',
            field=models.JSONField(default=list, help_text='\n        Пример структуры:\n        [\n            {\n                "node_id": "remedial-grammar-B1-02-9f3a2c",\n                "lesson_id": null,\n                "learning_objective": "grammar-B1-02",\n                "title": "Повтор: Past Simple vs Present Perfect",\n                "type": "remedial",\n                "status": "locked",\n                "prerequisites": ["lesson-42"],\n                "created_at": "2026-02-04T10:12:00Z",\n                "completed_at": null,\n                "metadata": {\n                    "source": "auto",\n                    "trigger": "multiple_failures"\n                }\n            },\n            ...\n        ]\n        ', verbose_name='Узлы пути'),
        ),
        migrations.CreateModel(
            name='MethodologicalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_data', models.JSONField()),
                ('total_units', models.PositiveIntegerField()),
                ('generated_units', models.PositiveIntegerField(default=0)),
                ('levels', models.JSONField(default=dict)),
                ('skills', models.JSONField(default=dict)),
                ('is_complete', models.BooleanField(default=False)),
                ('last_lesson_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plan', to='curriculum.course')),
            ],
            options={
                'verbose_name': 'Learning plan',
                'verbose_name_plural': 'Learning plans',
            },
        ),
    ]
