# Generated by Django 5.2.8 on 2026-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_learningpath_nodes_methodologicalplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='learning_objectives',
            field=models.ManyToManyField(help_text='Какие учебные цели проверяет задание', related_name='tasks', to='curriculum.learningobjective'),
        ),
        migrations.AlterField(
            model_name='lessoneventlog',
            name='event_type',
            field=models.CharField(choices=[('START', 'Начало урока'), ('COMPLETE', 'Завершение урока'), ('PAUSE', 'Пауза в уроке'), ('RESUME', 'Возобновление урока'), ('ABANDON', 'Покинул урок без завершения'), ('ASSESSMENT_START', 'Начало оценки урока'), ('ASSESSMENT_COMPLETE', 'Завершение оценки урока'), ('ASSESSMENT_ERROR', 'Ошибка оценки урока'), ('LEARNING_PATH_ADJUSTED', 'Сформирован следующий шаг учебного плана')], max_length=32, verbose_name='Тип события'),
        ),
    ]
