# Generated by Django 5.2.8 on 2026-02-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_alter_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassessmentresult',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assessments', to='curriculum.task'),
        ),
    ]
