# Generated by Django 5.2.8 on 2026-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_alter_taskassessmentresult_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкое'), ('medium', 'Среднее'), ('hard', 'Сложное')], default='medium', help_text='Легкое (0.5), Среднее (1.0), Сложное (2.0)', max_length=10, verbose_name='Сложность задания'),
        ),
    ]
