# Generated by Django 5.2.8 on 2025-11-16 07:47

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(validators=[users.models.Profile.validate_date_in_past], verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть введен в формате: '+79991234567'.", regex='^((\\+7)+([0-9]){10})$')], verbose_name='Телефон')),
                ('location', models.CharField(max_length=60, verbose_name='Город проживания')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, upload_to=users.models.Profile.create_path, verbose_name='Аватар пользователя')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Пользователь верифицирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('verify', 'Верифицировать'),),
            },
        ),
    ]
