# Generated by Django 5.2.8 on 2026-01-20 15:44

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(validators=[users.models.Profile.validate_date_in_past], verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть в международном формате (например, +79991234567). Допустимы цифры, начинается с + и кода страны, длина 1–15 цифр после +.', regex='^\\+?[1-9]\\d{1,14}$')], verbose_name='Телефон')),
                ('location', models.CharField(max_length=60, verbose_name='Город проживания')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, upload_to=users.models.Profile.create_path, verbose_name='Аватар пользователя')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Пользователь верифицирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('verify', 'Верифицировать'),),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, help_text="e.g., 'Business English', 'Academic Writing'", max_length=200, verbose_name='Specialization')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of Experience')),
                ('certification', models.TextField(blank=True, help_text='Teaching certificates and qualifications', verbose_name='Certification')),
                ('is_active_teacher', models.BooleanField(default=False, help_text='Can accept new students', verbose_name='Active Teacher')),
                ('max_students', models.PositiveIntegerField(default=50, help_text='Maximum number of active students', verbose_name='Maximum Students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('invite_code', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_level', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], default='A1', max_length=2, verbose_name='CEFR Level')),
                ('learning_goals', models.JSONField(blank=True, default=list, help_text="e.g., ['career', 'travel', 'business']", verbose_name='Learning Goals')),
                ('profession', models.CharField(blank=True, help_text='Professional context for personalization', max_length=200, verbose_name='Profession')),
                ('available_time_per_week', models.IntegerField(blank=True, null=True, verbose_name='Available Time Per Week (minutes)')),
                ('engagement_level', models.IntegerField(default=5, help_text='Scale 1-10', verbose_name='Engagement Level')),
                ('trust_level', models.IntegerField(default=4, help_text='Scale 1-10', verbose_name='Trust Level')),
                ('professional_context', models.TextField(blank=True, help_text='Detailed professional context for personalization', verbose_name='Professional Context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'indexes': [models.Index(fields=['english_level'], name='users_stude_english_fa4b4e_idx'), models.Index(fields=['engagement_level'], name='users_stude_engagem_f66d7c_idx'), models.Index(fields=['created_at'], name='users_stude_created_290fee_idx')],
            },
        ),
    ]
