# Generated by Django 5.2.8 on 2026-02-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='trust_level',
        ),
        migrations.AddField(
            model_name='student',
            name='confidence_level',
            field=models.FloatField(default=5, help_text='Уровень уверенности студента (1-10)'),
        ),
    ]
