# Generated by Django 5.2.8 on 2025-11-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_phone_telegramprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
