# Generated by Django 5.2.8 on 2025-11-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprofile',
            name='cefr_level',
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='available_time_per_week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='completed_lessons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='engagement_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='english_level',
            field=models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], default='A1', max_length=2, verbose_name='Уровень CEFR'),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='learning_goals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='learning_path',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='trust_level',
            field=models.IntegerField(default=4),
        ),
    ]
