# Generated by Django 5.2.8 on 2025-11-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_studyprofile_cefr_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprofile',
            name='completed_lessons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studyprofile',
            name='learning_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studyprofile',
            name='learning_path',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
