# Generated by Django 5.2.8 on 2025-11-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_studyprofile_completed_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprofile',
            name='available_time_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
