# Generated by Django 5.2.8 on 2025-11-28 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studyprofile_available_time_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть в международном формате (например, +79991234567). Допустимы цифры, начинается с + и кода страны, длина 1–15 цифр после +.', regex='^\\+?[1-9]\\d{1,14}$')], verbose_name='Телефон'),
        ),
    ]
