# Generated by Django 5.2.8 on 2025-11-30 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ai', 'Чат с AI'), ('group', 'Групповой чат'), ('notification', 'Уведомления'), ('telegram', 'Telegram чат')], default='ai', help_text='Определяет логику работы чата и доступные функции', max_length=20, verbose_name='Тип чата')),
                ('title', models.CharField(blank=True, help_text='Отображается в интерфейсе пользователя', max_length=255, verbose_name='Название чата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_ai_enabled', models.BooleanField(default=False, help_text='Разрешить использование AI в групповом чате', verbose_name='AI активен')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Используется для синхронизации с Telegram API', max_length=50, null=True, verbose_name='ID чата в Telegram')),
                ('notification_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_chats', to=settings.AUTH_USER_MODEL, verbose_name='Получатель уведомлений')),
                ('participants', models.ManyToManyField(help_text='Пользователи, имеющие доступ к чату', related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание сообщения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('is_ai', models.BooleanField(default=False, help_text='Помечает сообщение как сгенерированное AI', verbose_name='Сообщение от AI')),
                ('is_read', models.BooleanField(default=False, help_text='Статус прочтения для уведомлений и личных чатов', verbose_name='Прочитано')),
                ('source_type', models.CharField(choices=[('web', 'Веб-интерфейс'), ('telegram', 'Telegram'), ('api', 'Внешний API'), ('system', 'Системное сообщение')], default='web', help_text='Откуда пришло сообщение: веб, Telegram, API и т.д.', max_length=20, verbose_name='Источник сообщения')),
                ('external_id', models.CharField(blank=True, help_text='ID сообщения в источнике (например, message_id в Telegram)', max_length=100, null=True, verbose_name='Внешний ID сообщения')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего редактирования')),
                ('edit_count', models.PositiveIntegerField(default=0, verbose_name='Количество редактирований')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные от источника в формате JSON', verbose_name='Метаданные')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='Чат')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['type', '-created_at'], name='chat_chat_type_c0e803_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['telegram_chat_id'], name='chat_chat_telegra_19d212_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-timestamp'], name='chat_messag_chat_id_fa2313_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'timestamp'], name='chat_messag_is_read_974b12_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['source_type', '-timestamp'], name='chat_messag_source__3f553b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_id'], name='chat_messag_externa_437168_idx'),
        ),
    ]
