# Generated by Django 5.2.8 on 2026-01-20 15:44

import chat.models
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('web', 'Веб-интерфейс'), ('telegram', 'Telegram'), ('api', 'Внешний API'), ('whatsapp', 'WhatsApp')], default='web', max_length=20, verbose_name='Платформа')),
                ('scope', models.CharField(choices=[('private', 'Персональный чат'), ('group', 'Групповой чат'), ('system', 'Системные уведомления')], default='private', max_length=20, verbose_name='Тип чата')),
                ('is_ai_enabled', models.BooleanField(default=True, help_text='Разрешить использование AI в чате', verbose_name='AI активен')),
                ('external_chat_id', models.CharField(blank=True, help_text='Используется для синхронизации с внешними API', max_length=100, null=True, verbose_name='Внешний ID чата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='ai_assistant.aiassistant', verbose_name='AI-ассистент')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_chats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('participants', models.ManyToManyField(blank=True, related_name='group_chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание сообщения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('is_ai', models.BooleanField(default=False, help_text='Помечает сообщение как сгенерированное AI', verbose_name='Сообщение от AI')),
                ('is_read', models.BooleanField(default=False, help_text='Статус прочтения для уведомлений и личных чатов', verbose_name='Прочитано')),
                ('is_user_deleted', models.BooleanField(default=False, verbose_name='сообщение удалено пользователем')),
                ('source_type', models.CharField(choices=[('web', 'Веб-интерфейс'), ('telegram', 'Telegram'), ('api', 'Внешний API'), ('system', 'Системное сообщение')], default='web', help_text='Откуда пришло сообщение: веб, Telegram, API и т.д.', max_length=20, verbose_name='Источник сообщения')),
                ('external_id', models.CharField(blank=True, help_text='ID сообщения в источнике (например, message_id в Telegram)', max_length=100, null=True, verbose_name='Внешний ID сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего редактирования')),
                ('edit_count', models.PositiveIntegerField(default=0, verbose_name='Количество редактирований')),
                ('score', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='оценка')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные от источника в формате JSON', verbose_name='Метаданные')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('audio', 'Аудио'), ('video', 'Видео'), ('document', 'Документ')], default='text', max_length=20, verbose_name='Тип сообщения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='Чат')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='chat.message', verbose_name='ответ на')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=chat.models.MediaFile.media_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=chat.models.MediaFile.thumbnail_upload_path, verbose_name='Миниатюра')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Внешний ID файла в Telegram')),
                ('file_type', models.CharField(max_length=20)),
                ('mime_type', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('thumbnail_generated', models.BooleanField(default=False, verbose_name='Миниатюра сгенерирована')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='chat.message')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['owner', '-created_at'], name='chat_chat_owner_i_d37be6_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['platform', 'scope'], name='chat_chat_platfor_d375e2_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['external_chat_id'], name='chat_chat_externa_261013_idx'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('owner', 'ai_assistant', 'platform', 'scope'), name='unique_owner_ai_assistant_chat'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-timestamp'], name='chat_messag_chat_id_fa2313_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'timestamp'], name='chat_messag_is_read_974b12_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['source_type', '-timestamp'], name='chat_messag_source__3f553b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_id'], name='chat_messag_externa_437168_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='message_metadata_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['thumbnail_generated'], name='chat_mediaf_thumbna_3b2dda_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type', 'mime_type'], name='chat_mediaf_file_ty_3d9c42_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.UniqueConstraint(fields=('message', 'external_id'), name='unique_media_per_message'),
        ),
    ]
