# Generated by Django 5.2.8 on 2025-12-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_user_deleted',
            field=models.BooleanField(default=False, verbose_name='сообщение удалено пользователем'),
        ),
    ]
