# Generated by Django 5.2.8 on 2025-12-01 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_is_user_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_primary_ai_chat',
            field=models.BooleanField(default=False, help_text='Только один основной AI-чат на пользователя', verbose_name='Основной AI-чат'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Владелец персонального AI-чата', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'is_primary_ai_chat'], name='chat_chat_user_id_d326d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_ai_chat', True), ('type', 'ai')), fields=('user', 'is_primary_ai_chat'), name='unique_primary_ai_chat_per_user'),
        ),
    ]
