# Generated by Django 5.2.8 on 2025-12-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_is_primary_ai_chat_chat_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_user_deleted',
        ),
        migrations.AddField(
            model_name='message',
            name='is_user_deleted',
            field=models.BooleanField(default=False, verbose_name='сообщение удалено пользователем'),
        ),
    ]
