# Generated by Django 5.2.8 on 2025-12-01 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='оценка'),
        ),
    ]
