# Generated by Django 5.2.8 on 2025-12-02 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('chat', '0006_message_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_primary_ai_chat_per_user',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='chat_chat_type_c0e803_idx',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='chat_chat_telegra_19d212_idx',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='chat_chat_user_id_d326d8_idx',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_primary_ai_chat',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='notification_recipient',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='ai_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='ai_assistant.aiassistant', verbose_name='AI-ассистент'),
        ),
        migrations.AddField(
            model_name='chat',
            name='external_chat_id',
            field=models.CharField(blank=True, help_text='Используется для синхронизации с внешними API', max_length=100, null=True, verbose_name='Внешний ID чата'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_chats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='chat',
            name='platform',
            field=models.CharField(choices=[('web', 'Веб-интерфейс'), ('telegram', 'Telegram'), ('api', 'Внешний API'), ('whatsapp', 'WhatsApp')], default='web', max_length=20, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='chat',
            name='scope',
            field=models.CharField(choices=[('private', 'Персональный чат'), ('group', 'Групповой чат'), ('system', 'Системные уведомления')], default='private', max_length=20, verbose_name='Тип чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_ai_enabled',
            field=models.BooleanField(default=True, help_text='Разрешить использование AI в чате', verbose_name='AI активен'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='group_chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название чата'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['owner', '-created_at'], name='chat_chat_owner_i_d37be6_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['platform', 'scope'], name='chat_chat_platfor_d375e2_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['external_chat_id'], name='chat_chat_externa_261013_idx'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('owner', 'ai_assistant'), name='unique_owner_ai_assistant_chat'),
        ),
    ]
