# Generated by Django 5.2.8 on 2025-12-02 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_aiassistant_learning_goals_and_more'),
        ('chat', '0007_remove_chat_unique_primary_ai_chat_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_owner_ai_assistant_chat',
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('owner', 'ai_assistant', 'platform', 'scope'), name='unique_owner_ai_assistant_chat'),
        ),
    ]
