# Generated by Django 5.2.8 on 2025-12-10 16:42

import chat.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_mediafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Внешний ID файла в Telegram'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.MediaFile.thumbnail_upload_path, verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=chat.models.MediaFile.media_upload_path),
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.UniqueConstraint(fields=('message', 'external_id'), name='unique_media_per_message'),
        ),
    ]
