# Generated by Django 5.2.8 on 2025-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_mediafile_external_id_mediafile_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('audio', 'Аудио'), ('video', 'Видео'), ('document', 'Документ')], default='text', max_length=20, verbose_name='Тип сообщения'),
        ),
    ]
