# Generated by Django 5.2.8 on 2025-12-12 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'Медиафайл', 'verbose_name_plural': 'Медиафайлы'},
        ),
        migrations.AddField(
            model_name='mediafile',
            name='thumbnail_generated',
            field=models.BooleanField(default=False, verbose_name='Миниатюра сгенерирована'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['thumbnail_generated'], name='chat_mediaf_thumbna_3b2dda_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type', 'mime_type'], name='chat_mediaf_file_ty_3d9c42_idx'),
        ),
    ]
