# Generated by Django 5.2.8 on 2025-12-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_mediafile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='title',
        ),
    ]
