# Generated by Django 5.2.8 on 2025-12-22 17:44

import curriculum.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('vocabulary', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('listening', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reading', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('writing', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('speaking', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_level', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], help_text='Уровень CEFR, на котором эта цель актуальна', max_length=2, verbose_name='CEFR Level')),
                ('skill_domain', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], help_text='Область языкового навыка', max_length=20, verbose_name='Skill Domain')),
                ('order_in_level', models.PositiveSmallIntegerField(default=1, help_text='Порядковый номер цели в рамках уровня и области (для сортировки)', verbose_name='Order within level and domain')),
                ('name', models.CharField(help_text="Clear, actionable objective — e.g., 'Use Past Simple correctly in work emails'", max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional detailed explanation for methodologists', verbose_name='Description')),
                ('identifier', models.SlugField(editable=False, help_text="Auto-generated unique ID like 'grammar-B1-01'", unique=True, verbose_name='Machine Identifier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Learning Objective',
                'verbose_name_plural': 'Learning Objectives',
                'ordering': ['cefr_level', 'skill_domain', 'order_in_level'],
                'indexes': [models.Index(fields=['cefr_level', 'skill_domain'], name='curriculum__cefr_le_a4e68a_idx'), models.Index(fields=['identifier'], name='curriculum__identif_0ab93b_idx')],
                'unique_together': {('cefr_level', 'skill_domain', 'order_in_level')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('target_cefr_from', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], max_length=2, verbose_name='From CEFR')),
                ('target_cefr_to', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], max_length=2, verbose_name='To CEFR')),
                ('estimated_duration', models.PositiveIntegerField(help_text='Total estimated time to complete the course', verbose_name='Estimated Duration (minutes)')),
                ('required_skills', models.JSONField(default=list, help_text="e.g., ['grammar:B1', 'listening:A2']", verbose_name='Required Skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('learning_objectives', models.ManyToManyField(to='curriculum.learningobjective', verbose_name='Learning Objectives')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('content', models.JSONField(help_text='Optional structured lesson instructions or narrative for AI', verbose_name='Content')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Duration (minutes)')),
                ('required_cefr', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], max_length=2, verbose_name='Required CEFR')),
                ('skill_focus', models.JSONField(default=list, help_text="e.g., ['listening', 'vocabulary']", validators=[curriculum.validators.validate_skill_focus], verbose_name='Skill Focus')),
                ('adaptive_parameters', models.JSONField(default=dict, help_text="e.g., {'min_correct_ratio': 0.7, 'max_items': 10}", verbose_name='Adaptive Parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.course', verbose_name='Course')),
                ('learning_objectives', models.ManyToManyField(to='curriculum.learningobjective', verbose_name='Learning Objectives')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short, machine-readable name (e.g., 'backend', 'standup-meetings')", max_length=50, unique=True, verbose_name='Tag Name')),
                ('description', models.CharField(blank=True, help_text='Human-readable explanation for admins', max_length=200, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Professional Tag',
                'verbose_name_plural': 'Professional Tags',
                'indexes': [models.Index(fields=['name'], name='curriculum__name_f1db3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], max_length=2, null=True, verbose_name='Current CEFR Level')),
                ('professional_context', models.TextField(blank=True, help_text="e.g., 'Backend developer in fintech. Need English for stand-ups and documentation.'", verbose_name='Professional Context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='SkillTrajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('grammar', 'Грамматика'), ('vocabulary', 'Лексика'), ('reading', 'Чтение'), ('listening', 'Аудирование'), ('writing', 'Письмо'), ('speaking', 'Говорение')], max_length=32)),
                ('trend', models.FloatField(default=0.0)),
                ('stability', models.FloatField(default=0.0)),
                ('plateau_detected', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_trajectories', to='curriculum.student')),
            ],
        ),
        migrations.CreateModel(
            name='SkillSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar', models.FloatField(default=0.0)),
                ('vocabulary', models.FloatField(default=0.0)),
                ('listening', models.FloatField(default=0.0)),
                ('reading', models.FloatField(default=0.0)),
                ('writing', models.FloatField(default=0.0)),
                ('speaking', models.FloatField(default=0.0)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='curriculum.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.course', verbose_name='Course')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_enrollments', to='curriculum.lesson', verbose_name='Current Lesson')),
                ('progress_snapshot', models.ForeignKey(blank=True, help_text='Последний зафиксированный снимок навыков', null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.skillsnapshot', verbose_name='Progress Snapshot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('final_cefr', models.CharField(blank=True, choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], max_length=2, null=True, verbose_name='Final CEFR')),
                ('skill_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.currentskillprofile', verbose_name='Skill Profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Diagnostic Session',
                'verbose_name_plural': 'Diagnostic Sessions',
            },
        ),
        migrations.AddField(
            model_name='currentskillprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to='curriculum.student'),
        ),
        migrations.CreateModel(
            name='CurrentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('grammar', 'Грамматика'), ('vocabulary', 'Лексика'), ('reading', 'Чтение'), ('listening', 'Аудирование'), ('writing', 'Письмо'), ('speaking', 'Говорение')], max_length=32)),
                ('score', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_skills', to='curriculum.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, verbose_name='Text Response')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='responses/', verbose_name='Audio Response')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('is_correct', models.BooleanField(blank=True, help_text='True/False for closed questions, None for open-ended', null=True, verbose_name='Is Correct (Auto)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Task Response',
                'verbose_name_plural': 'Student Task Responses',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_version', models.CharField(blank=True, max_length=50, verbose_name='LLM Version')),
                ('raw_output', models.JSONField(verbose_name='Raw LLM Output')),
                ('structured_feedback', models.JSONField(verbose_name='Structured Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('task_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studenttaskresponse', verbose_name='Task Response')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20, verbose_name='Task Type')),
                ('response_format', models.CharField(choices=[('multiple_choice', 'Multiple Choice – выбор одного или нескольких вариантов'), ('single_choice', 'Single Choice – выбор одного варианта'), ('short_text', 'Short Text – краткий текстовый ответ, 1–3 слова'), ('free_text', 'Free Text – развёрнутый ответ, абзац или текст'), ('audio', 'Audio – голосовое сообщение')], max_length=20, verbose_name='Response Format')),
                ('content', models.JSONField(verbose_name='Content')),
                ('content_schema_version', models.CharField(default='v1', verbose_name='Content Schema')),
                ('difficulty_cefr', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], max_length=2, verbose_name='Difficulty CEFR')),
                ('is_diagnostic', models.BooleanField(default=False, verbose_name='Used in Diagnostic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='curriculum.lesson', verbose_name='Lesson')),
                ('professional_tags', models.ManyToManyField(blank=True, to='curriculum.professionaltag', verbose_name='Professional Tags')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.AddField(
            model_name='studenttaskresponse',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.task', verbose_name='Task'),
        ),
        migrations.CreateModel(
            name='LessonTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_code', models.CharField(help_text='Код решения decision engine (advance, repeat, remedial, etc.)', max_length=128)),
                ('teacher_override', models.BooleanField(default=False, help_text='Было ли решение переопределено преподавателем')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_transitions', to='curriculum.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_transitions', to='curriculum.enrollment')),
                ('from_lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='curriculum.lesson')),
                ('to_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='curriculum.lesson')),
                ('skill_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_transitions', to='curriculum.skillsnapshot')),
                ('task', models.ForeignKey(blank=True, help_text='Task, на основании которого было принято решение (если применимо)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_transitions', to='curriculum.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=30, verbose_name='Error Type')),
                ('example', models.TextField(verbose_name='Example')),
                ('correction', models.TextField(blank=True, verbose_name='Correction')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Detected At')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolved')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.student', verbose_name='Student')),
                ('context_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.task', verbose_name='Context Task')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_enrollments', to='curriculum.task', verbose_name='Current Task'),
        ),
        migrations.CreateModel(
            name='TaskMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_media/', verbose_name='File')),
                ('media_type', models.CharField(choices=[('text', 'Raw text snippet or prompt'), ('audio', 'Audio file (e.g., MP3, WAV)'), ('video', 'Video file (e.g AVI, MP4)'), ('image', 'Image (e.g., diagram, screenshot)'), ('document', 'PDF, DOC, or other document')], max_length=20, verbose_name='Media Type')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='curriculum.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task Media',
                'verbose_name_plural': 'Task Media',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='TeacherOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_decision', models.CharField(max_length=32)),
                ('overridden_decision', models.CharField(max_length=32)),
                ('reason', models.TextField(help_text='Объяснение преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_overrides', to='curriculum.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='curriculum.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Override',
                'verbose_name_plural': 'Teacher Overrides',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='curriculum__course__d8682d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['cefr_level'], name='curriculum__cefr_le_021c08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skilltrajectory',
            unique_together={('student', 'skill')},
        ),
        migrations.AddIndex(
            model_name='diagnosticsession',
            index=models.Index(fields=['student'], name='curriculum__student_472051_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticsession',
            index=models.Index(fields=['completed_at'], name='curriculum__complet_0bba40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='currentskill',
            unique_together={('student', 'skill')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['task_response'], name='curriculum__task_re_5a63bc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='curriculum__task_ty_abb4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['response_format'], name='curriculum__respons_b586c8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['difficulty_cefr'], name='curriculum__difficu_21adcf_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_diagnostic'], name='curriculum__is_diag_82f412_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttaskresponse',
            index=models.Index(fields=['student'], name='curriculum__student_9f2af5_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttaskresponse',
            index=models.Index(fields=['task'], name='curriculum__task_id_7a3265_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttaskresponse',
            index=models.Index(fields=['submitted_at'], name='curriculum__submitt_2b5462_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['student'], name='curriculum__student_53532c_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['error_type'], name='curriculum__error_t_b02c70_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['resolved'], name='curriculum__resolve_3aae0b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course'], name='curriculum__student_e62215_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active'], name='curriculum__is_acti_e42fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['last_activity'], name='curriculum__last_ac_7ab071_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'course', 'is_active'), name='unique_active_enrollment'),
        ),
        migrations.AddIndex(
            model_name='taskmedia',
            index=models.Index(fields=['task'], name='curriculum__task_id_36bd62_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmedia',
            index=models.Index(fields=['media_type'], name='curriculum__media_t_ff8980_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheroverride',
            index=models.Index(fields=['student'], name='curriculum__student_1184a6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheroverride',
            index=models.Index(fields=['lesson'], name='curriculum__lesson__594383_idx'),
        ),
    ]
