# Generated by Django 5.2.8 on 2025-12-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_errorlog_student_alter_skilltrajectory_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Задание актуально'),
        ),
    ]
