# Generated by Django 5.2.8 on 2025-12-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_task_options_and_more'),
        ('users', '0009_student_teacher_delete_studyprofile_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studenttaskresponse',
            name='curriculum__student_9f2af5_idx',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='current_task',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assessment_job_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assessment Job ID'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assessment_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assessment Started At'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lesson_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED_TASKS', 'All tasks completed'), ('PENDING_ASSESSMENT', 'Pending assessment'), ('ASSESSMENT_ERROR', 'Assessment error'), ('COMPLETED', 'Lesson completed')], default='ACTIVE', max_length=20, verbose_name='Lesson Status'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='theory_content',
            field=models.TextField(blank=True, help_text='HTML content with theory and explanations', verbose_name='Theory Content'),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_transitions', to='curriculum.assessment'),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='from_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='curriculum.lesson'),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Task, на основании которого было принято решение (если применимо)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_transitions', to='curriculum.task'),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='to_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='curriculum.lesson'),
        ),
        migrations.AlterField(
            model_name='studenttaskresponse',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_response', to='curriculum.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20, verbose_name='Task Type'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['lesson_status'], name='curriculum__lesson__c99c06_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['assessment_job_id'], name='curriculum__assessm_d05d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttaskresponse',
            index=models.Index(fields=['student', 'task'], name='response_student_task_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['lesson', 'is_active', 'order'], name='task_lesson_active_order_idx'),
        ),
    ]
