# Generated by Django 5.2.8 on 2025-12-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_remove_studenttaskresponse_curriculum__student_9f2af5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttaskresponse',
            name='is_correct',
        ),
    ]
