# Generated by Django 5.2.8 on 2025-12-27 18:22

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_remove_studenttaskresponse_is_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontransition',
            options={'verbose_name': 'Lesson Transition', 'verbose_name_plural': 'Lesson Transitions'},
        ),
        migrations.RenameField(
            model_name='lessontransition',
            old_name='created_at',
            new_name='transition_at',
        ),
        migrations.AddField(
            model_name='lessontransition',
            name='decision_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lessontransition',
            name='decision_rationale',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='lessontransition',
            name='override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessontransition',
            name='skill_trajectory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='curriculum.skilltrajectory'),
        ),
        migrations.AddField(
            model_name='lessontransition',
            name='teacher_override_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessontransition',
            name='transition_type',
            field=models.CharField(choices=[('TASK_LEVEL', 'Task Level Transition'), ('LESSON_LEVEL', 'Lesson Level Transition')], default='TASK_LEVEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='curriculum.assessment'),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='decision_code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='curriculum.enrollment'),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='from_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curriculum.lesson'),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='skill_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='curriculum.skillsnapshot'),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='curriculum.task'),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='teacher_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessontransition',
            name='to_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curriculum.lesson'),
        ),
        migrations.AddIndex(
            model_name='lessontransition',
            index=models.Index(fields=['enrollment', 'transition_at'], name='curriculum__enrollm_96c9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='lessontransition',
            index=models.Index(fields=['from_lesson', 'to_lesson'], name='curriculum__from_le_ce4adc_idx'),
        ),
        migrations.AddIndex(
            model_name='lessontransition',
            index=models.Index(fields=['transition_type'], name='curriculum__transit_e7cb36_idx'),
        ),
        migrations.AddIndex(
            model_name='lessontransition',
            index=models.Index(fields=['teacher_override'], name='curriculum__teacher_7ea27d_idx'),
        ),
    ]
