# Generated by Django 5.2.8 on 2025-12-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_lessontransition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttaskresponse',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Audio Transcript'),
        ),
    ]
