# Generated by Django 5.2.8 on 2025-12-30 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_studenttaskresponse_transcript'),
        ('users', '0009_student_teacher_delete_studyprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_type', models.CharField(choices=[('LINEAR', 'Линейный (по порядку уроков курса)'), ('ADAPTIVE', 'Адаптивный (с ветвлениями по SkillDelta)'), ('PERSONALIZED', 'Персонализированный (AI-генерированный под цели/профессию)')], default='LINEAR', max_length=20, verbose_name='Тип пути')),
                ('nodes', models.JSONField(default=list, help_text='\n        Пример структуры:\n        [\n            {\n                "node_id": 1,\n                "lesson_id": 5,\n                "title": "Grammar: Present Simple",\n                "prerequisites": [], \n                "triggers": [\n                    {"condition": "skill_delta.speaking < 0", "action": "add_remedial", "remedial_lesson_id": 12}\n                ],\n                "status": "completed",  // in_progress, locked, recommended\n                "completed_at": "2025-12-28T15:30:00Z"\n            },\n            ...\n        ]\n        ', verbose_name='Узлы пути')),
                ('current_node_index', models.PositiveIntegerField(default=0, help_text='Позиция в массиве nodes', verbose_name='Индекс текущего узла')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время генерации пути')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="e.g., {'generated_by': 'gpt-4o-mini', 'based_on_profile': {'level': 'B1', 'goal': 'IT_interview'}}", verbose_name='Метаданные')),
            ],
            options={
                'verbose_name': 'Учебный путь',
                'verbose_name_plural': 'Учебные пути',
            },
        ),
        migrations.CreateModel(
            name='SkillDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deltas', models.JSONField(help_text="{'grammar': +0.10, 'speaking': -0.03, 'overall': +0.08}")),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='skillsnapshot',
            options={'ordering': ['-snapshot_at'], 'verbose_name': 'Снимок навыков', 'verbose_name_plural': 'Снимки навыков'},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress_snapshot',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='adaptive_path_enabled',
            field=models.BooleanField(default=False, verbose_name='Адаптивный путь активен'),
        ),
        migrations.AddField(
            model_name='skillsnapshot',
            name='associated_lesson',
            field=models.ForeignKey(blank=True, help_text='Урок, после завершения которого сделан снимок (POST). Для PRE используем урок, который студент собирается начать.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_snapshots', to='curriculum.lesson', verbose_name='Связанный урок'),
        ),
        migrations.AddField(
            model_name='skillsnapshot',
            name='enrollment',
            field=models.ForeignKey(blank=True, help_text='Контекст курса для адаптивных маршрутов', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='curriculum.enrollment', verbose_name='Зачисление'),
        ),
        migrations.AddField(
            model_name='skillsnapshot',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="e.g., {'source': 'assessment', 'lesson_score': 0.92, 'tasks_completed': 10}", verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='skillsnapshot',
            name='skills',
            field=models.JSONField(default=dict, help_text="{'grammar': 0.85, 'vocabulary': 0.78, 'speaking': 0.65, 'listening': 0.82, ...} — 0.0–1.0", verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='skillsnapshot',
            name='snapshot_context',
            field=models.CharField(choices=[('POST_LESSON', 'После завершения урока'), ('PLACEMENT', 'Результат placement test'), ('WEEKLY_SUMMARY', 'Еженедельный'), ('MANUAL', 'Ручной')], default='POST_LESSON', max_length=20, verbose_name='Контекст снимка'),
        ),
        migrations.AlterField(
            model_name='skillsnapshot',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='users.student', verbose_name='Студент'),
        ),
        migrations.AlterUniqueTogether(
            name='skillsnapshot',
            unique_together={('enrollment', 'associated_lesson')},
        ),
        migrations.AddIndex(
            model_name='skillsnapshot',
            index=models.Index(fields=['student', '-snapshot_at'], name='curriculum__student_78df35_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsnapshot',
            index=models.Index(fields=['enrollment', 'associated_lesson'], name='curriculum__enrollm_a42891_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsnapshot',
            index=models.Index(fields=['snapshot_context'], name='curriculum__snapsho_0dbd5a_idx'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='enrollment',
            field=models.OneToOneField(help_text='Один путь на одно зачисление', on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to='curriculum.enrollment', verbose_name='Зачисление'),
        ),
        migrations.AddField(
            model_name='skilldelta',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_deltas', to='curriculum.enrollment'),
        ),
        migrations.AddField(
            model_name='skilldelta',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_deltas', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='skilldelta',
            name='post_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deltas_as_post', to='curriculum.skillsnapshot'),
        ),
        migrations.AddField(
            model_name='skilldelta',
            name='pre_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deltas_as_pre', to='curriculum.skillsnapshot'),
        ),
        migrations.AddField(
            model_name='skilldelta',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_deltas', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='skilldelta',
            unique_together={('student', 'lesson')},
        ),
    ]
