# Generated by Django 5.2.8 on 2025-12-30 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_learningpath_skilldelta_alter_skillsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsnapshot',
            name='enrollment',
            field=models.ForeignKey(help_text='Контекст курса для адаптивных маршрутов', on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='curriculum.enrollment', verbose_name='Зачисление'),
        ),
    ]
