# Generated by Django 5.2.8 on 2025-12-30 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_alter_skillsnapshot_enrollment'),
        ('users', '0009_student_teacher_delete_studyprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('START', 'Начало урока'), ('COMPLETE', 'Завершение урока'), ('PAUSE', 'Пауза в уроке'), ('RESUME', 'Возобновление урока'), ('ABANDON', 'Покинул урок без завершения'), ('ASSESSMENT_START', 'Начало оценки урока'), ('ASSESSMENT_COMPLETE', 'Завершение оценки урока')], max_length=32, verbose_name='Тип события')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время события')),
                ('channel', models.CharField(choices=[('WEB', 'Веб-приложение'), ('BOT', 'Telegram-бот'), ('API', 'Внешний API')], default='WEB', help_text='Откуда пришло событие — для кросс-канальной аналитики', max_length=20, verbose_name='Канал')),
                ('duration_minutes', models.DecimalField(blank=True, decimal_places=2, help_text='Автоматически рассчитывается для COMPLETE по разнице с START', max_digits=6, null=True, verbose_name='Длительность (мин)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Дополнительные данные: e.g., {'completed_tasks': 8, 'total_tasks': 10, 'score': 0.92}", verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(help_text='Контекст курса и текущего прогресса', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_events', to='curriculum.enrollment', verbose_name='Зачисление')),
                ('lesson', models.ForeignKey(help_text='Конкретный урок, к которому относится событие', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='curriculum.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(help_text='Ссылка на профиль студента с уровнем, целями и профессией', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_events', to='users.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Событие урока',
                'verbose_name_plural': 'События уроков',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', '-timestamp'], name='curriculum__student_6843f8_idx'), models.Index(fields=['enrollment', 'lesson'], name='curriculum__enrollm_b0f3ca_idx'), models.Index(fields=['event_type', 'timestamp'], name='curriculum__event_t_fc4121_idx'), models.Index(fields=['channel'], name='curriculum__channel_b28441_idx')],
            },
        ),
    ]
