# Generated by Django 5.2.8 on 2025-12-30 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_lessoneventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoneventlog',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Конкретный урок, к которому относится событие', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='curriculum.lesson', verbose_name='Урок'),
        ),
    ]
