# Generated by Django 5.2.8 on 2026-01-20 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, help_text="Форма слова, как она встречается в тексте (например, 'running').", max_length=255, unique=True, verbose_name='Слово')),
                ('canonical_form', models.CharField(blank=True, help_text="Инфинитив для глаголов, единственное число для существительных и т.д. (например, 'run').", max_length=255, null=True, verbose_name='Базовая форма')),
                ('pos', models.CharField(help_text='Part of Speech: noun, verb, adjective и т.д.', max_length=50, verbose_name='Часть речи')),
                ('lang_code', models.CharField(default='en', help_text="ISO 639-1 код языка (например, 'en' для английского).", max_length=10, verbose_name='Код языка')),
                ('ipa', models.CharField(blank=True, help_text='Пример: /ˈrʌnɪŋ/', max_length=100, null=True, verbose_name='Международная фонетическая транскрипция (IPA)')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='WordForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(help_text="Конкретная грамматическая форма (например, 'ran', 'mice').", max_length=255, verbose_name='Форма')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Нормализованные метки, например: ['past', 'singular'].", verbose_name='Стандартизированные теги')),
                ('raw_tags', models.JSONField(blank=True, default=list, help_text='Как указано в источнике данных.', verbose_name='Исходные теги')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='word_helper.word', verbose_name='Базовое слово')),
            ],
            options={
                'verbose_name': 'Грамматическая форма',
                'verbose_name_plural': 'Грамматические формы',
            },
        ),
        migrations.CreateModel(
            name='WordSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.TextField(help_text='Пояснение значения слова на простом английском или с переводом.', verbose_name='Объяснение / Перевод')),
                ('raw_tags', models.JSONField(blank=True, default=list, help_text="Исходные теги из источника (например, ['countable']).", verbose_name='Необработанные теги')),
                ('categories', models.JSONField(blank=True, default=list, help_text="Классификация значения (например, ['Past participles']).", verbose_name='Категории')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='word_helper.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Значение слова',
                'verbose_name_plural': 'Значения слов',
            },
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_type', models.CharField(choices=[('random', 'Random Voice'), ('uk_female', 'UK English – Female'), ('us_male', 'US English – Male')], default='random', help_text='Определяет акцент и пол голоса для произношения.', max_length=50, verbose_name='Тип голоса')),
                ('audio_file', models.FileField(blank=True, help_text='Файл произношения в формате MP3 или WAV.', null=True, upload_to='word_audio/', verbose_name='Аудиофайл')),
                ('source', models.CharField(blank=True, help_text='Откуда взят файл: Wiktionary, Google TTS, AWS Polly и т.д.', max_length=100, verbose_name='Источник')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='word_helper.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Произношение',
                'verbose_name_plural': 'Произношения',
                'unique_together': {('word', 'voice_type')},
            },
        ),
    ]
